Feat: 헤더 컴포넌트 제작
part4-team9/GlobalNomad pull request #10
Opened 2024-07-26 13:16 UTC by hongseoha

## 🏷️ 이슈 번호 

- close #3 

## 🧱 작업 사항
- 아직 별 기능 없는 헤더입니다. 조건에 따라 로그인상태인지 아닌지정도만 분리 해 뒀습니다.
## 📸 결과물
![image](https://github.com/user-attachments/assets/75741ea6-f14a-461e-9552-c57a0d3fd921)
![image](https://github.com/user-attachments/assets/cbdd4bf3-7756-4d47-97ec-359aed069d31)

## 💬 공유 포인트 및 논의 사항
- 로고 클릭시 메인페이지로 가야하지만 아직 페이지 네이밍을 못해서 못 넣었습니다. 그냥 main으로 넣으면 될까요?

2024-07-26 14:30 UTC, i-nooo-2 requested changes
태그 변경 및 반응형 대응을 위한 스타일 수정이 필요합니다.

2024-07-26 14:30 UTC, i-nooo-2 commented on app/layout.tsx
시멘틱 태그에 맞게 구성한다면, header는 body 태그 위에 있어야 합니다!
헤더 컴포넌트를 body 밖으로 빼주세요.

혹시 body에 relative 속성은 왜 주신걸까요??

2024-07-26 14:30 UTC, i-nooo-2 commented on app/_components/header/index.tsx
> +export default async function Header() {
해당 async 는 불필요해보입니다.
혹시 헤더 컴포넌트 내에서 비동기 작업을 할 일이 있을까요??
아니라면 제거 부탁드립니다!

2024-07-26 14:30 UTC, i-nooo-2 commented on app/_components/header/_component/header-not-login.tsx
HeaderNotLogin 이라는 이름보다는 GuestHeader 가 더 적합해보입니다만,,
취향의 영역이니 편하게 스루해주세요~

2024-07-26 14:30 UTC, i-nooo-2 commented on app/_components/header/index.tsx
- 헤더 내 HeaderNotLogin의 y기준 위치가 맞지 않습니다. flex를 통해 가운데에 맞추는 작업이 필요해보여요.
- `<Image src={logoWithTitle} alt="Logo" />` 또한 위치가 맞지 않네요. 이건 1px 정도라 고치기 힘든 부분이면 스루해주세요.
- section 태그를 단순 스타일링 용도로 쓰는 것은 올바르지 않은 것 같습니다.  section 태그는 큰 덩어리의 콘텐츠를 주제별로 나누는 역할을 하며, 문서의 독립된 부분을 나타냅니다. 지금 코드에서는 div 태그가 더 적절해보여요. 다른 컴포넌트에서의 section 태그 사용도 부적절해보입니다.
- 반응형 padding 맞지 않습니다.

2024-07-26 15:06 UTC, hongseoha commented on app/layout.tsx
body에 relative는 작업 도중 오류가 나서 추가했던 부분인데 방금 제거하고 확인해봤더니 문제가 다시 발생하지 않네요. 제거했습니다!
그리고 html 내에는 head와 body만 품을 수 있어서 body 위로 빼면 오류가 발생하지 않나요?

2024-07-26 15:13 UTC, hongseoha commented on app/_components/header/index.tsx
> +export default async function Header() {
아 저쪽은 당장 쓰이진 않는데, 로그인 여부에 따라서 아래 비로그인/로그인 여부 보여줄 생각이었어요. 지금 당장은 안 쓰이니까 빼고 머지하고 나중에 쓰일때 다른 코드랑 같이 작업하는 게 기록상 낫겠네요.

2024-07-26 15:58 UTC, i-nooo-2 commented on app/layout.tsx
아잇
제가 완전 착각하고 있었네요.........!!!!!!!!!!!!!!!
맞습니다!!!!!!! 악 잊어주세요 ㅋㅋㅠ

2024-07-26 17:20 UTC, hongseoha commented on app/_components/header/index.tsx
수정사항들 반영 완료되었습니다~ 시간 나실 때 확인 부탁드려요!

2024-07-26 18:05 UTC, edhcoding approved these changes
고생하셨습니다! 많이 수정하셔서 제가 보기에는 좋은 것 같습니다!

2024-07-27 02:38 UTC, eunbinnie approved these changes
고생많으셨습니다! 👍🏻 헤더 아주 깔끔하고 좋네용

2024-07-27 02:38 UTC, eunbinnie commented on app/_components/header/_component/guest-header.tsx
> +      <div className='text-m flex gap-[25px] pt-1'>
요기에서 padding top 보다는 위에 부모 nav에서 flex, items-center를 하면 상하 가운데 맞춤이 더 정확할 것 같습니다! 부모에서 flex로 정렬하면 UserHeader 컴포넌트도 가운데 정렬될 것 같습니다!

2024-07-27 03:45 UTC, yubugi commented
확인했습니다 팀원분들이 수정사항 말씀해주신게 수정되면 머지해도 좋을것 같습니다

2024-07-27 03:48 UTC, yubugi commented
요구사항에 맞춰서 계속 수정해주셨네요 고생하셨습니다!

2024-07-27 06:20 UTC, i-nooo-2 approved these changes
layout.tsx 부분만 수정하면 될 것 같아요!!!
수고하셨습니다!!! 👍👍👍

+) 정말 혹시몰라 다시 언급합니다만, 여전히 린트가 작동되지 않는 것 같아서요! 작동 확인 부탁드립니다 🥲

2024-07-27 06:20 UTC, i-nooo-2 commented on app/layout.tsx
>          <Providers>{children}</Providers>
지금 children 페이지들이 Header 한테 깔려서 가려집니다!
```
<Providers><main className='{헤더높이만큼 margin부여}'>{children}</main></Providers>
```
이런식으로 따로 처리를 해줘야 할 것 같아요.

2024-07-27 07:34 UTC, merged