Feat: 버튼 컴포넌트 제작
part4-team9/GlobalNomad pull request #12
Opened 2024-07-26 14:56 UTC by yubugi

## 🏷️ 이슈 번호 

- close #8

## 🧱 작업 사항

버튼 컴포넌트 제작

## 📸 결과물

![버튼 컴포넌트 캡처](https://github.com/user-attachments/assets/47c7895d-ad21-4731-b8fa-32d13721132b)

## 💬 공유 포인트 및 논의 사항
테일윈드가 아직 익숙하지 않아서 시간이 많이 걸렸습니다 ㅠㅠ 부족한점이 많을 것 같은데 의견 남겨주시면 감사합니다!

사용할 때는 className으로 디자인 하고, fontSize로 폰트 크기, disabled는 버튼 비활성화 입니다.
![사용](https://github.com/user-attachments/assets/78246016-2eb9-4b29-acec-328144594190)

2024-07-26 15:51 UTC, i-nooo-2 requested changes
- border radius가 4px, 6px, 8px, 15px 등 여러 경우가 있어서 props 로 받아서 적용해주셔야 할 것 같습니다.
- hover 시 색변화가 아닌 선택되었을 때 (clicked) 배경색 변화인 것 같아요! 호버는 임의 색상을 주어야 할 것 같습니다.

2024-07-27 03:35 UTC, yubugi commented
> * border radius가 4px, 6px, 8px, 15px 등 여러 가지 경우에 해당하는 props를 로 받아 적용해 볼 것입니다.
> * hover 시 색상변화가 아닌 변형 모양일 때 (clicked) 배경색 변화인 것 같아요! 호버는 색상을 할 것 같습니다.

넵 확인하고 수정하겠습니다

2024-07-27 03:37 UTC, yubugi commented
> * border radius가 4px, 6px, 8px, 15px 등 여러 경우가 있어서 props 로 받아서 적용해주셔야 할 것 같습니다.
> * hover 시 색변화가 아닌 선택되었을 때 (clicked) 배경색 변화인 것 같아요! 호버는 임의 색상을 주어야 할 것 같습니다.

확인하고 수정하겠습니다! 감사합니다

2024-07-27 03:41 UTC, yubugi commented
확인하고 수정하겠습니다! 감사합니다

2024-07-29 17:29 UTC, eunbinnie approved these changes
고생많으셨습니다!👍🏻 코멘트 확인해주시면 감사드리겠습니다~ 추후 버튼 컴포넌트 사용하면서 궁금한 점 생기면 질문드리겠습니다!

2024-07-29 17:29 UTC, eunbinnie commented on app/_components/button/index.tsx
> +  variant: 'select' | 'action';
select, action을 봤을 때 어떤 디자인인지 파악하기 조금 어려워서 배경색을 기준으로 black | white로 받으면 좀 더 이해하기 쉬울 것 같습니다!

2024-07-29 17:29 UTC, eunbinnie commented on app/_components/button/index.tsx
> +    <button className={buttonStyle} onClick={onClick} disabled={disabled} type="button" style={{ borderRadius }}>
여기에서 타입을 button으로 고정하는 것 보다는 props 구조분해할당할 때 기본값으로 type='button'을 하면 좋을 것 같습니다! submit 용도로 버튼을 쓰는 경우도 있을 것 같아서요

2024-07-30 03:15 UTC, edhcoding commented on app/_components/button/index.tsx
> +  variant,
variant가 필수 값 인데 기본값 넣어주는 건 어떻까요?

2024-07-30 04:01 UTC, yubugi commented on app/_components/button/index.tsx
> +  variant: 'select' | 'action';
넵 알겠습니다!

2024-07-30 04:02 UTC, yubugi commented on app/_components/button/index.tsx
> +    <button className={buttonStyle} onClick={onClick} disabled={disabled} type="button" style={{ borderRadius }}>
확인하고 수정하겠습니다!

2024-07-30 04:02 UTC, yubugi commented on app/_components/button/index.tsx
> +  variant,
생각을 못했네요 확인했습니다!

2024-07-30 13:45 UTC, hongseoha approved these changes
깔끔하네요~👍👍 jsdoc에 사용 예시 함께 보여주시거나 하면 사용할 때 좀 더 편할 것 같아요! 승인 해 두겠습니다!

2024-07-31 22:48 UTC, i-nooo-2 approved these changes
수고하셨습니다! 진짜 자잘하게 수정할 부분 리뷰 남겨놓았습니다. 확인부탁드려요~~~

2024-07-31 22:48 UTC, i-nooo-2 commented on app/_components/button/index.tsx
> + * @property isSelected - 버튼이 선택 여부 결정 ture이면 색상변화
true 오타 났어요~~!

2024-07-31 22:48 UTC, i-nooo-2 commented on app/_components/button/index.tsx
> + * @interface ButtonProps
interface가 아니라 button 컴포넌트에게 jsdoc를 적용시켜주셨으면 좋겠습니다!

2024-08-01 09:49 UTC, merged